language: objective-c
xcode_project: EchoTipCalc.xcodeproj
xcode_scheme: EchoTipCalc
xcode_sdk: iphonesimulator8.3

script:
- xcodebuild clean build test -project EchoTipCalc.xcodeproj -scheme EchoTipCalcTests


