language: objective-c
xcode_project: EchoTipCalc.xcodeproj
xcode_scheme: EchoTipCalc
env:
  global:
    - IOS_SDK="iphonesimulator10.0"
    - IOS10_DESTINATION="OS=10.0,name=iPhone 6"

script:
- xcodebuild clean build test -project EchoTipCalc.xcodeproj -scheme EchoTipCalc



